# constants
C = 16
D = -2

# grind conastants
X_GRID_SIZE = 4
Y_GRID_SIZE = 4
GRID_INCREMENT = 0.1

# contour constants
CONTOURS = 35

# gradient constants
INPUT_SPACE_OFFSET = -65
CONE_SCALE = 0.035
GRADIENT_DATA_SELECTION = 2
VECTOR_SELECTION_X = 3
VECTOR_SELECTION_Y = 2.25

# paricle grid constants
X_PARTICLE_GRID_SIZE = 3
Y_PARTICLE_GRID_SIZE = 3
PARTICLE_GRID_INCREMENT = 0.3

# animation constants
NUMBER_OF_ITERATIONS = 100
GRADIENT_SCALING = 0.0005
